### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by ibexa-crowdin**

### CODE REVIEW

**Review by adamwojs — CHANGES_REQUESTED** [review]
This update seems to be broken

**Comment by fkeloks** [comment]
Hello,

We've added some translations.
When will you merge this PR please? Is it possible to get it in 4.5?

Thanks

**Comment by adamwojs** [comment]
@mikadamczyk Could you please take a look on this PR?

**Comment by reithor** [comment]
@mikadamczyk 
I have done some tests:
https://issues.ibexa.co/browse/IBX-7507 : a lot of missing translations when using latest  release (4.6.0-beta4)
https://issues.ibexa.co/browse/IBX-7508 : error from pluralization when using https://github.com/ibexa/i18n/tree/l10n_main

so from what I see, a lot of polish translations that use pluralization need 3 options :

```
      <trans-unit id="b3caf2127ff7fb3fd977af365ec4f104d6ab7687" resname="diff.ago.hour">
        <source>1 hour ago|%count% hours ago</source>
        <target state="translated">1 godzinę temu|%count% godzin temu</target>
        <note>key: diff.ago.hour</note>
      </trans-unit>
```
should use
```
 <target state="translated">1 godzinę temu|%count% godzin temu|%count% ...something else...</target>
 ```

**Pull request merged**
